from setuptools import setup

setup(
    name='FriendorFoe',
    version='v1.0b',
    packages=['venv.lib.python3.5.site-packages.mako', 'venv.lib.python3.5.site-packages.mako.ext',
              'venv.lib.python3.5.site-packages.past', 'venv.lib.python3.5.site-packages.past.tests',
              'venv.lib.python3.5.site-packages.past.types', 'venv.lib.python3.5.site-packages.past.utils',
              'venv.lib.python3.5.site-packages.past.builtins', 'venv.lib.python3.5.site-packages.past.translation',
              'venv.lib.python3.5.site-packages.pytz', 'venv.lib.python3.5.site-packages.yaml',
              'venv.lib.python3.5.site-packages.numpy', 'venv.lib.python3.5.site-packages.numpy.ma',
              'venv.lib.python3.5.site-packages.numpy.ma.tests', 'venv.lib.python3.5.site-packages.numpy.doc',
              'venv.lib.python3.5.site-packages.numpy.fft', 'venv.lib.python3.5.site-packages.numpy.fft.tests',
              'venv.lib.python3.5.site-packages.numpy.lib', 'venv.lib.python3.5.site-packages.numpy.lib.tests',
              'venv.lib.python3.5.site-packages.numpy.core', 'venv.lib.python3.5.site-packages.numpy.core.tests',
              'venv.lib.python3.5.site-packages.numpy.f2py', 'venv.lib.python3.5.site-packages.numpy.f2py.tests',
              'venv.lib.python3.5.site-packages.numpy.tests', 'venv.lib.python3.5.site-packages.numpy.compat',
              'venv.lib.python3.5.site-packages.numpy.linalg', 'venv.lib.python3.5.site-packages.numpy.linalg.tests',
              'venv.lib.python3.5.site-packages.numpy.random', 'venv.lib.python3.5.site-packages.numpy.random.tests',
              'venv.lib.python3.5.site-packages.numpy.testing', 'venv.lib.python3.5.site-packages.numpy.testing.tests',
              'venv.lib.python3.5.site-packages.numpy.testing.nose_tools',
              'venv.lib.python3.5.site-packages.numpy.distutils',
              'venv.lib.python3.5.site-packages.numpy.distutils.tests',
              'venv.lib.python3.5.site-packages.numpy.distutils.command',
              'venv.lib.python3.5.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.5.site-packages.numpy.matrixlib',
              'venv.lib.python3.5.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.5.site-packages.numpy.polynomial',
              'venv.lib.python3.5.site-packages.numpy.polynomial.tests', 'venv.lib.python3.5.site-packages.future',
              'venv.lib.python3.5.site-packages.future.moves', 'venv.lib.python3.5.site-packages.future.moves.dbm',
              'venv.lib.python3.5.site-packages.future.moves.html',
              'venv.lib.python3.5.site-packages.future.moves.http',
              'venv.lib.python3.5.site-packages.future.moves.test',
              'venv.lib.python3.5.site-packages.future.moves.urllib',
              'venv.lib.python3.5.site-packages.future.moves.xmlrpc',
              'venv.lib.python3.5.site-packages.future.moves.tkinter', 'venv.lib.python3.5.site-packages.future.tests',
              'venv.lib.python3.5.site-packages.future.types', 'venv.lib.python3.5.site-packages.future.utils',
              'venv.lib.python3.5.site-packages.future.builtins', 'venv.lib.python3.5.site-packages.future.backports',
              'venv.lib.python3.5.site-packages.future.backports.html',
              'venv.lib.python3.5.site-packages.future.backports.http',
              'venv.lib.python3.5.site-packages.future.backports.test',
              'venv.lib.python3.5.site-packages.future.backports.email',
              'venv.lib.python3.5.site-packages.future.backports.email.mime',
              'venv.lib.python3.5.site-packages.future.backports.urllib',
              'venv.lib.python3.5.site-packages.future.backports.xmlrpc',
              'venv.lib.python3.5.site-packages.future.standard_library', 'venv.lib.python3.5.site-packages.pygame',
              'venv.lib.python3.5.site-packages.pygame.docs', 'venv.lib.python3.5.site-packages.pygame.gp2x',
              'venv.lib.python3.5.site-packages.pygame.tests',
              'venv.lib.python3.5.site-packages.pygame.tests.test_utils',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.all_ok',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.exclude',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.timeout',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.failures1',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.everything',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.incomplete',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.print_stderr',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.print_stdout',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.infinite_loop',
              'venv.lib.python3.5.site-packages.pygame.tests.run_tests__tests.incomplete_todo',
              'venv.lib.python3.5.site-packages.pygame.threads', 'venv.lib.python3.5.site-packages.pygame.examples',
              'venv.lib.python3.5.site-packages.serial', 'venv.lib.python3.5.site-packages.iso8601',
              'venv.lib.python3.5.site-packages.dateutil', 'venv.lib.python3.5.site-packages.dateutil.tz',
              'venv.lib.python3.5.site-packages.dateutil.zoneinfo', 'venv.lib.python3.5.site-packages.markdown',
              'venv.lib.python3.5.site-packages.markdown.extensions', 'venv.lib.python3.5.site-packages.markupsafe',
              'venv.lib.python3.5.site-packages.matplotlib', 'venv.lib.python3.5.site-packages.matplotlib.tri',
              'venv.lib.python3.5.site-packages.matplotlib.axes', 'venv.lib.python3.5.site-packages.matplotlib.cbook',
              'venv.lib.python3.5.site-packages.matplotlib.style', 'venv.lib.python3.5.site-packages.matplotlib.tests',
              'venv.lib.python3.5.site-packages.matplotlib.compat',
              'venv.lib.python3.5.site-packages.matplotlib.testing',
              'venv.lib.python3.5.site-packages.matplotlib.testing._nose',
              'venv.lib.python3.5.site-packages.matplotlib.testing._nose.plugins',
              'venv.lib.python3.5.site-packages.matplotlib.testing.jpl_units',
              'venv.lib.python3.5.site-packages.matplotlib.backends',
              'venv.lib.python3.5.site-packages.matplotlib.backends.qt_editor',
              'venv.lib.python3.5.site-packages.matplotlib.sphinxext',
              'venv.lib.python3.5.site-packages.matplotlib.sphinxext.tests',
              'venv.lib.python3.5.site-packages.matplotlib.projections', 'venv.lib.python3.5.site-packages.libfuturize',
              'venv.lib.python3.5.site-packages.libfuturize.fixes',
              'venv.lib.python3.5.site-packages.mpl_toolkits.tests',
              'venv.lib.python3.5.site-packages.mpl_toolkits.mplot3d',
              'venv.lib.python3.5.site-packages.mpl_toolkits.axes_grid',
              'venv.lib.python3.5.site-packages.mpl_toolkits.axes_grid1',
              'venv.lib.python3.5.site-packages.mpl_toolkits.axisartist',
              'venv.lib.python3.5.site-packages.libpasteurize', 'venv.lib.python3.5.site-packages.libpasteurize.fixes',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip.req',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip.vcs',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip.utils',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip.compat',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip.models',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.distlib',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.colorama',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.lockfile',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.progress',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.packaging',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.webencodings',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip.commands',
              'venv.lib.python3.5.site-packages.pip-9.0.1-py3.5.egg.pip.operations', 'WorkingBuild'],
    url='',
    license='',
    author='FriendorFoe Team',
    author_email='',
    description=''
)
