# CAR SPECIFIC VALUES
CENTER = 1500
MAX_RIGHT = 1000
MAX_LEFT = 2000
MAX_DEGREE_TURN = 50

NEUTRAL = 1500
MAX_SPEED = 1800
TEST_SPEED = 1700
MAX_VELOCITY = 13.4  # m/s
MIN_MOVE_SPEED = 1567

# DERIVED CAR VALUES
DEGREE_GRADIENT = (MAX_LEFT - MAX_RIGHT) / MAX_DEGREE_TURN
VELOCITY_GRADIENT = (MAX_SPEED - NEUTRAL) / MAX_VELOCITY

NUM_DRONES = 3

ESC = 3
STEERING = 5

# TODO Change this on getting server information from customer
# SIMULATION SERVER
SERVER_BASE_ADDRESS = 'http://localhost/cgi-bin'
SERVER_POST_ADDRESS = '/post_gps_data.cgi'
SERVER_GET_ADDRESS = '/get_velocity_vector.cgi'

# AREA OF OPERATION DIMENSIONS
ORIGIN_LATITUDE = 29.189537
ORIGIN_LONGITUDE = -81.046341
CORNER_LAT = 29.198097
CORNER_LONG = -81.046161
ROTATION_ANGLE = -45

LENGTH_X = 90
LENGTH_Y = 120
